DataDir: /Users/lina/Documents/FROHMAGE/Input_data/simulated/
FLUXCONV_NC: 0.0009609999999999999
LH: /Users/lina/Documents/FROHMAGE/Input_data/simulated/Lh.fits
LM: /Users/lina/Documents/FROHMAGE/Input_data/simulated/Lm.fits
OutputDir: Output/NGC7469/
PSF_HS: /Users/lina/Documents/FROHMAGE/Input_data/simulated/H_fft.fits
PSF_MS: /Users/lina/Documents/FROHMAGE/Input_data/simulated/G_fft.fits
d: 3
downsampling: 3
fact_pad: 41
hyper_image: /Users/lina/Documents/FROHMAGE/Input_data/simulated/NIRSpec_subcube.fits
lacp: 10
multi_image: /Users/lina/Documents/FROHMAGE/Input_data/simulated/NIRCam_multi.fits
nc: 180
nr: 180
