DataDir: Input/simulated_data
OutputDir: Output/simulated_data/
hyper_image: Input/simulated_data/NIRSpec_subcube.fits
multi_image: Input/simulated_data/NIRCam_multi.fits
LH: Input/simulated_data/Lh.fits
LM: Input/simulated_data/Lm.fits
PSF_HS: Input/simulated_data/H_fft.fits
PSF_MS: Input/simulated_data/G_fft.fits
'FLUXCONV_NC: 0.0009609999999999999
downsampling: 3
fact_pad: 41
lacp: 10
nc: 180
nr: 180
mu: 10
