ConvConst: 205000
FLUXCONV_NC: 0.0009609999999999999
InputDir: /Users/lina/Documents/Thesis/MyFusionProject/Input/Data_1
NIRCam_Filters:
- f115w
- f140m
- f150w
- f150w2
- f162m
- f164n
- f182m
- f187n
- f200w
- f210m
- f212n
NIRCam_SpectralResponses: /Users/lina/Documents/Thesis/MyFusionProject/Input/Data_1/NirCam_SpectralResponse.fits
NIRSpec_Filters: f100lp
NIRSpec_SpectralResponses: /Users/lina/Documents/Thesis/MyFusionProject/Input/Data_1/NirSpec_Throughput_f100lp.fits
PSF_HS: /Users/lina/Documents/Thesis/MyFusionProject/Input/Data_1/PSF_HS.fits
PSF_MS: /Users/lina/Documents/Thesis/MyFusionProject/Input/Data_1/PSF_MS.fits
TableWave: /Users/lina/Documents/Thesis/MyFusionProject/Input/Data_1/NirSpec_Throughput_f100lp.fits
exp_time: 128.841
hyper_image: /Users/lina/Documents/Thesis/MyFusionProject/Input/Data_1/NIRSpec_subcube.fits
multi_image: /Users/lina/Documents/Thesis/MyFusionProject/Input/Data_1/NIRCam_cube.fits
